Update ci-basics.yml

diff --git a/.github/workflows/ci-basics.yml b/.github/workflows/ci-basics.yml
--- a/.github/workflows/ci-basics.yml
+++ b/.github/workflows/ci-basics.yml
@@ -33,6 +33,8 @@ jobs:
         run: |
           echo "Listing app folder:"
           ls -la app
+          echo "Listing s3buket folder:"
+          ls -la app/s3buket
 
       - name: 🔍 Check installed tools
         run: |
@@ -75,7 +77,7 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
           SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
         run: |
-          echo "Running Maven build from app directory..."
+          echo "Running Maven build from:"
           pwd
           ls -la
           mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
@@ -86,13 +88,13 @@ jobs:
       - name: 📄 Verify Sonar report file
         run: |
           echo "Checking if report-task.txt exists..."
-          ls -la app/.scannerwork || echo ".scannerwork folder not found"
-          cat app/.scannerwork/report-task.txt || echo "report-task.txt not found"
+          ls -la app/s3buket/.scannerwork || echo ".scannerwork folder not found"
+          cat app/s3buket/.scannerwork/report-task.txt || echo "report-task.txt not found"
 
       - name: 🚦 SonarQube Quality Gate
         uses: SonarSource/sonarqube-quality-gate-action@v1
         with:
-          scanMetadataReportFile: app/.scannerwork/report-task.txt
+          scanMetadataReportFile: app/s3buket/.scannerwork/report-task.txt
         env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
 
